version: '3'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=enotulen_prod
    ports:
      - '54321:5432'
    volumes:
      - database-volume:/var/lib/postgresql/data
    restart: on-failure
  backend:
    build: .
    image: enotulen-be
    environment:
      - PORT=8080
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/enotulen_prod
    depends_on:
      - db
    ports:
      - '8080:8080'
    restart: unless-stopped
  frontend:
    image: ryanb1303/enotulen-fe
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  database-volume: {}
